# Generated by Django 6.0.5 on 2026-05-17 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrower', '0002_borrower_group'),
        ('groups', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('total_installment', models.FloatField()),
                ('per_install_amount', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Aproved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrower.borrower')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
