# Generated by Django 6.0.5 on 2026-05-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('total_installment', models.IntegerField()),
                ('per_install_amount', models.FloatField()),
            ],
        ),
    ]
